package Treenipvk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Treenipvk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.04 15:25:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoiteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi135 */
  @Test
  public void testRekisteroi135() {    // Harjoite: 135
    Harjoite harjoite1 = new Harjoite(); 
    Harjoite harjoite2 = new Harjoite(); 
    harjoite1.rekisteroi(); 
    harjoite2.rekisteroi(); 
    assertEquals("From: Harjoite line: 140", harjoite2.getId() - 1, harjoite1.getId()); 
  } // Generated by ComTest END
}