package Treenipvk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Treenipvk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.06 21:44:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivakirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa36 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa36() throws SailoException {    // Paivakirja: 36
    Paivakirja paivakirja = new Paivakirja(); 
    Treeni treeni1 = new Treeni(); treeni1.rekisteroi(); 
    Treeni treeni2 = new Treeni(); treeni2.rekisteroi(); 
    paivakirja.lisaa(treeni1); assertEquals("From: Paivakirja line: 41", 1, paivakirja.getTreeneja()); 
    paivakirja.lisaa(treeni2); assertEquals("From: Paivakirja line: 42", 2, paivakirja.getTreeneja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa121 */
  @Test
  public void testLisaa121() {    // Paivakirja: 121
    Paivakirja paivakirja = new Paivakirja(); 
    Harjoite harjoite1 = new Harjoite(); harjoite1.rekisteroi(); 
    Harjoite harjoite2 = new Harjoite(); harjoite2.rekisteroi(); 
    paivakirja.lisaa(harjoite1); assertEquals("From: Paivakirja line: 125", 1, paivakirja.getHarjoitteita()); 
    paivakirja.lisaa(harjoite2); assertEquals("From: Paivakirja line: 126", 2, paivakirja.getHarjoitteita()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa204 */
  @Test
  public void testLisaa204() {    // Paivakirja: 204
    Paivakirja paivakirja = new Paivakirja(); 
    Sarja sarja1 = new Sarja(); sarja1.rekisteroi(); 
    Sarja sarja2 = new Sarja(); sarja2.rekisteroi(); 
    paivakirja.lisaa(sarja1); assertEquals("From: Paivakirja line: 208", 1, paivakirja.getSarjoja()); 
    paivakirja.lisaa(sarja2); assertEquals("From: Paivakirja line: 209", 2, paivakirja.getSarjoja()); 
  } // Generated by ComTest END
}