package Treenipvk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Treenipvk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.06 21:44:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SarjaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi118 */
  @Test
  public void testRekisteroi118() {    // Sarja: 118
    Sarja sarja1 = new Sarja(); 
    Sarja sarja2 = new Sarja(); 
    sarja1.rekisteroi(); 
    sarja2.rekisteroi(); 
    assertEquals("From: Sarja line: 123", sarja2.getId() - 1, sarja1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone174 */
  @Test
  public void testClone174() {    // Sarja: 174
    Sarja sarja1 = new Sarja(80, 5); 
    Sarja sarja2 = sarja1.clone(); 
    assertEquals("From: Sarja line: 177", sarja2.getTyopaino(), sarja1.getTyopaino(), 0.000001); 
    assertEquals("From: Sarja line: 178", sarja2.getToistot(), sarja1.getToistot()); 
  } // Generated by ComTest END
}