package Treenipvk.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import Treenipvk.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.06 21:37:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SarjatTest {



  // Generated by ComTest BEGIN
  /** testGetSarja56 */
  @Test
  public void testGetSarja56() {    // Sarjat: 56
    Sarjat sarjat = new Sarjat(); 
    Sarja sarja1 = new Sarja(); sarja1.rekisteroi(); sarja1.setHarid(0); sarjat.lisaaSarja(sarja1); 
    Sarja sarja2 = new Sarja(); sarja2.rekisteroi(); sarja1.setHarid(1); sarjat.lisaaSarja(sarja2); 
    Sarja sarja3 = new Sarja(); sarja3.rekisteroi(); sarja1.setHarid(1); sarjat.lisaaSarja(sarja3); 
    assertEquals("From: Sarjat line: 61", 1, sarjat.getSarja(1).getId()); 
    assertEquals("From: Sarjat line: 62", 2, sarjat.getSarja(2).getId()); 
    assertEquals("From: Sarjat line: 63", 3, sarjat.getSarja(3).getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSarjat80 */
  @Test
  public void testGetSarjat80() {    // Sarjat: 80
    Sarjat sarjat = new Sarjat(); 
    Sarja sarja1 = new Sarja(); sarja1.rekisteroi(); sarja1.setHarid(0); sarjat.lisaaSarja(sarja1); 
    Sarja sarja2 = new Sarja(); sarja2.rekisteroi(); sarja2.setHarid(1); sarjat.lisaaSarja(sarja2); 
    Sarja sarja3 = new Sarja(); sarja3.rekisteroi(); sarja3.setHarid(1); sarjat.lisaaSarja(sarja3); 
    ArrayList<Sarja> found = new ArrayList<>(sarjat.getSarjat(1)); 
    assertEquals("From: Sarjat line: 87", 1, found.get(0).getHarid()); 
    assertEquals("From: Sarjat line: 88", 1, found.get(1).getHarid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista177 */
  @Test
  public void testPoista177() {    // Sarjat: 177
    Sarjat sarjat = new Sarjat(); 
    Sarja sarja1 = new Sarja(); sarja1.rekisteroi(); sarjat.lisaaSarja(sarja1); 
    Sarja sarja2 = new Sarja(); sarja2.rekisteroi(); sarjat.lisaaSarja(sarja2); 
    Sarja sarja3 = new Sarja(); sarja3.rekisteroi(); sarjat.lisaaSarja(sarja3); 
    int id = sarja2.getId(); 
    sarjat.poista(id); 
    assertEquals("From: Sarjat line: 184", null, sarjat.getSarja(id)); 
  } // Generated by ComTest END
}