package Treenipvk.test;
// Generated by ComTest BEGIN
import java.time.LocalDate;
import static org.junit.Assert.*;
import org.junit.*;
import Treenipvk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.06 21:36:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi109 */
  @Test
  public void testRekisteroi109() {    // Treeni: 109
    Treeni treeni1 = new Treeni(); 
    Treeni treeni2 = new Treeni(); 
    treeni1.rekisteroi(); 
    treeni2.rekisteroi(); 
    assertEquals("From: Treeni line: 114", treeni2.getId() - 1, treeni1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone171 */
  @Test
  public void testClone171() {    // Treeni: 171
    Treeni treeni1 = new Treeni("testi", LocalDate.now()); 
    Treeni treeni2 = treeni1.clone(); 
    assertEquals("From: Treeni line: 175", true, treeni1.getNimi().equals(treeni2.getNimi())); 
    assertEquals("From: Treeni line: 176", true, treeni1.getPvm().equals(treeni2.getPvm())); 
  } // Generated by ComTest END
}