package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.04 15:44:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TarkistusTest {



  // Generated by ComTest BEGIN
  /** testTarkistaInteger50 */
  @Test
  public void testTarkistaInteger50() {    // Tarkistus: 50
    Tarkistus tarkistus = new Tarkistus(); 
    assertEquals("From: Tarkistus line: 52", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaInteger("21.12")); 
    assertEquals("From: Tarkistus line: 53", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaInteger("21.12")); 
    assertEquals("From: Tarkistus line: 54", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaInteger("21.1e")); 
    assertEquals("From: Tarkistus line: 55", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaInteger("2f.12")); 
    assertEquals("From: Tarkistus line: 56", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaInteger("2.2.2")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaDouble68 */
  @Test
  public void testTarkistaDouble68() {    // Tarkistus: 68
    Tarkistus tarkistus = new Tarkistus(); 
    assertEquals("From: Tarkistus line: 70", null, tarkistus.tarkistaDouble("21.12")); 
    assertEquals("From: Tarkistus line: 71", null, tarkistus.tarkistaDouble("21.12")); 
    assertEquals("From: Tarkistus line: 72", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaDouble("21.1e")); 
    assertEquals("From: Tarkistus line: 73", "Käytä numeroarvojen kohdalla vain numeroita!", tarkistus.tarkistaDouble("2f.12")); 
    assertEquals("From: Tarkistus line: 74", "Erottele numerot desimaaleista vain yhdellä pisteellä!", tarkistus.tarkistaDouble("2.2.2")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaPvm87 */
  @Test
  public void testTarkistaPvm87() {    // Tarkistus: 87
    Tarkistus tarkistus = new Tarkistus(); 
    assertEquals("From: Tarkistus line: 89", null, tarkistus.tarkistaPvm("1.1.2021")); 
    assertEquals("From: Tarkistus line: 90", null, tarkistus.tarkistaPvm("1.2.2019")); 
    assertEquals("From: Tarkistus line: 91", null, tarkistus.tarkistaPvm("2.3.2000")); 
    assertEquals("From: Tarkistus line: 92", "Tarkista arvojen erotukset ja että kaikki arvot on täytetty!", tarkistus.tarkistaPvm("1.1.1.2021")); 
    assertEquals("From: Tarkistus line: 93", "Kuukauden pitää olla alle 13!", tarkistus.tarkistaPvm("2.13.2000")); 
    assertEquals("From: Tarkistus line: 94", "Päivämäärä liian suuri asettamallesi kuukaudelle!", tarkistus.tarkistaPvm("30.2.2021")); 
    assertEquals("From: Tarkistus line: 95", "Et voi kirjata merkintöjä tulevaisuuteen!", tarkistus.tarkistaPvm("28.2.2121")); 
  } // Generated by ComTest END
}